spring:
  application:
    name: lostfound
  config:
    import: optional:file:.env[.properties],optional:file:./config/application-local.yml,optional:classpath:application-local.yml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 50
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  cloud:
    aws:
      s3:
        region: us-east-1

app:
  s3:
    bucket: lostfoundstorage

file:
  upload-dir: ./uploads

server:
  port: ${SERVER_PORT:${PORT:5000}}
